### ISSUE TITLE
Speed task module

### ISSUE THREAD

**Issue by Dash-QC** [crackhex/TAS-Comp-Bot-py#12]
The speed task module; timed competitions, usually running for a few hours. 

How it works: After the task is started in speed task mode, people may $requesttask, which will give them the task in DM (previously set by /speed-task-desc command). They have a until a set deadline (set by hosts, with /speed-task-time). They may only submit if they have requested task.

**Host commands:**
- [x] `$/speedtasklength` sets the duration (in hours) of the speed task
   - [x] If not set, defaults to 4
- [x] `$/speedtaskdesc` sets the description of the speed task (i.e. the task itself)
- [x] `$/speedtaskreminders` sets reminder times
   - [x] All arguments are integers which determine the times (in minutes) reminders will be sent, can add as many arguments as necessary.
   - [x] If not set, defaults to every multiple of 60 smaller than the length, and 10 (e.g. `180 120 60 10` for default length)
- [x] `$/togglereminderpings` toggles `@everyone` pings for public reminders
   - [x] If not set, defaults to False. Every time the command is used it switches between True and False.

**Public command:**
- [x] `$/requesttask` sends the task in a DM to the user, as well as their custom deadline. They can only request once per task.

**Comp logic:**
- [x] A speed task is started by passing the speed task parameter as 1 in `/start-task`
   - [x] A new `deadline` parameter is added, according to #15 
   - [x] A new `is_released` parameter is added
   - [x] If no description has been set, the bot sends ``Please set the task description with `$speedtaskdesc`!``
   - [x] When the speed task is started, create a SpeedTask table that stores these columns: "user_id", "end_time" (unix timestamp of deadline for said user), "active" (0 or 1 boolean).
- [x] Users who have requested the task may submit like usual before their deadline
   - [x] Name added to the submission list upon first submission
   - [x] Assigned the Submitted role at custom deadline, unlike #8 
   - [x] Users are reminded of their deadline at each set reminder
      - [x] The bot sends `You have <time> remaining to submit!`
      - [x] `<time>` is formatted as `<hours> hours and <minutes> minutes`
         - [x] If `<hours>` = 1, then make sure "hours" is singular
         - [x] If `<minutes>` = 1, then make sure "minutes" is singular
         - [x] If `<minutes>` = 0, then exclude the minutes portion of the message
   - [x] Once their deadline has passed, they may no longer submit. "active" is set to 0 in their row of the SpeedTask db.
      - [x] The bot sends `Your time is up! Thank you for participating in Task <task_num>.`
      - [x] If the user tries to submit, the bot sends `You can't submit, your time is up!`
         - [x] If the user never submitted, the bot instead sends `You can't submit, your time is up! If you wish to send in a late submission, please DM the current host so they can add your submission manually.`
- [x] Users who haven't requested the task are denied.
   - [x] The bot sends ``You may not submit yet! Use `$requesttask` first.``
- [x] Task is sent in #tasks at (deadline - length) and `is_released` is set to 1
   - [x] The bot sends `@everyone Task {task_num} has been released publicly! You have until <t:{unix_deadline}:t> (<t:{unix_deadline}:R>) to submit to this speed task! Please see <#{tasks_channel}> for task information.`
   - [x] Once `is_released` is 1, _all_ users may submit like usual until the final deadline
   - [x] Ensure those who requested the task after (deadline - 2*length) retain their custom deadline
   - [x] Ensure submission list and Submitted role work exactly the same way as a pre-release submission
   - [x] Reminders are sent in #announcements at each set reminder
      - [x] If `reminderpings` is False, the bot sends `Reminder: You have <time> remaining to submit!`
      - [x] If `reminderpings` is True, the bot sends `@everyone Reminder: You have <time> remaining to submit!`
   - [x] If users try to use `$requesttask`, the bot sends `The task has already been posted publicly! Please see <#tasks_channel_id> for task information.`
   - [x] If users try to use `$requesttask` while no task is running, the bot sends `There is no active speed task yet.`
   - [x] Similarly, if users try to use `$requesttask` during a non-speed task, the bot sends `This is not a speed task! Please see <#tasks_channel_id> for task information.`
- [x] Task closes, according to #15 
   - [x] The bot sends `@everyone Task <task_num> is over! Thank you to everyone who participated!`
- [x] Description is cleared automatically, to prevent the host of the next speed task from failing to add theirs
- [x] Add a comment in the code crediting Xander, as most of these messages are directly copied from the old bot

**Comment by kierio04** [comment]
Transferred list to main comment

**Comment by kierio04** [comment]
Closing thanks to #18
